name: flashcards
description: "A simple flashcard app for learning and memorization with multi-language support."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  file_picker: ^8.0.0+1
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/flash_cards.png"

flutter:
  assets:
    - assets/lang/en.json
    - assets/lang/tr.json
    - assets/lang/de.json
    - assets/flash_cards.png
  uses-material-design: true
